name: basic_flutter_app_assign
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ghosts.jpg
    - assets/images/lake_rocks.jpg
    - assets/images/sea.jpg
  fonts:
    - family: MonaSans
      fonts:
        - asset: assets/fonts/MonaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/MonaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/MonaSans-Regular.ttf

